# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('kwd', models.CharField(blank=True, max_length=250)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('img', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование категории')),
                ('slug', models.CharField(max_length=250, verbose_name='url')),
                ('desc', models.CharField(blank=True, max_length=250, verbose_name='Описание категории')),
                ('kwd', models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова категории')),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('kwd', models.CharField(blank=True, max_length=250)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('img', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Svoistvo_tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование свойства')),
                ('text', models.CharField(max_length=200, verbose_name='Свойство')),
            ],
            options={
                'verbose_name': 'Свойство товара',
                'verbose_name_plural': 'Свойства товаров',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('slug', models.CharField(max_length=250, verbose_name='url')),
                ('desc', models.CharField(blank=True, max_length=250, verbose_name='Описание товара')),
                ('kwd', models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова товара')),
                ('text', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='svoistvo_tovar',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.Tovar'),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='tovar',
            unique_together=set([('slug',)]),
        ),
    ]
