# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование категории')),
                ('desc', models.CharField(default='', max_length=250, verbose_name='Описание категории')),
                ('kwd', models.CharField(default='', max_length=250, verbose_name='Ключевые слова категории')),
                ('tetx', models.TextField()),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('desc', models.CharField(default='', max_length=250, verbose_name='Описание товара')),
                ('kwd', models.CharField(default='', max_length=250, verbose_name='Ключевые слова товара')),
                ('tetx', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
