# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_category_tovar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magazin.Category'),
            preserve_default=False,
        ),
    ]
