# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_tovar_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tetx',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='tetx',
            new_name='text',
        ),
    ]
