# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_auto_20160516_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
