# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0005_auto_20160517_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
