# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0006_auto_20160517_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svoistvo_tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование свойства')),
                ('text', models.CharField(max_length=200, verbose_name='Свойство')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.Tovar')),
            ],
        ),
    ]
