# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0007_svoistvo_tovar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svoistvo_tovar',
            options={'verbose_name': 'Свойство товара', 'verbose_name_plural': 'Свойства товаров'},
        ),
    ]
