# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0008_auto_20160517_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kwd',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова категории'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='desc',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='kwd',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова товара'),
        ),
    ]
