# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0009_auto_20160517_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=22, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovar',
            name='slug',
            field=models.SlugField(default=22, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
