# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0012_auto_20160517_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=250, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='slug',
            field=models.CharField(max_length=250, verbose_name='url'),
        ),
    ]
